# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6351691d565907423edfe538118c9ca3a079d0c08caa19f571a0a608e08ebf1a920f166a3c3b89bff53262b5e4049baaf2b810672ae5b21fc1e4321b4e9948bb

test:
  secret_key_base: 580b2ec7feb225ab283dbd732982837660a80100e935d28679c6a610685d7e6fee29404da1d92c526a6425962660d6fd1b8e8cf8318045d8f5986b7335986e32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
